-- migrations/004_insights.sql
-- AI insights generated by Gemini, one row per generation attempt.
-- We use the most recent row per account; older rows kept as history.

CREATE TABLE IF NOT EXISTS public.ai_insights (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id           UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  account_id        UUID NOT NULL REFERENCES public.accounts(id) ON DELETE CASCADE,
  trades_count      INTEGER NOT NULL,
  observations      TEXT[] NOT NULL DEFAULT '{}',
  blindspots        TEXT[] NOT NULL DEFAULT '{}',
  discipline_notes  TEXT,
  generated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ai_insights_account_idx
  ON public.ai_insights (account_id, generated_at DESC);

ALTER TABLE public.ai_insights ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users select own insights" ON public.ai_insights;
DROP POLICY IF EXISTS "Service role all insights" ON public.ai_insights;

-- Users can READ their own insights; service role writes them.
CREATE POLICY "Users select own insights" ON public.ai_insights
  FOR SELECT TO authenticated USING (user_id = auth.uid());

CREATE POLICY "Service role all insights" ON public.ai_insights
  FOR ALL TO service_role USING (TRUE) WITH CHECK (TRUE);
